name: Build and Release OP Media Downloader

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build for Windows
        run: yarn run build:win

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: op-media-downloader-windows
          path: dist/*.exe

  build-mac-intel:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build for macOS (Intel)
        env:
          ARCH: x64
          CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
          CERT_PASSWORD: ${{ secrets.MAC_SECRET_KEY }}
        run: |
          # Create and unlock a temporary keychain
          security create-keychain -p "$CERT_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$CERT_PASSWORD" build.keychain

          # Decode the Base64 certificate
          echo "$CERTIFICATE" | base64 --decode > certificate.p12

          # Import the certificate into the keychain
          security import certificate.p12 -A -P "$CERT_PASSWORD" -k build.keychain

          # Explicitly trust the imported certificate
          CERT_HASH=$(security find-identity -v -p codesigning build.keychain | awk '/OnPage/ {print $2}')
          security set-key-partition-list -S apple-tool:,apple: -s -k "$CERT_PASSWORD" build.keychain

          # Verify identities for code signing
          security find-identity -v -p codesigning build.keychain

          # Run the build
          yarn run build:mac

      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v3
        with:
          name: op-media-downloader-mac-intel
          path: dist/*.dmg

  build-mac-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build for macOS (ARM)
        env:
          ARCH: arm64
          CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
          CERT_PASSWORD: ${{ secrets.MAC_SECRET_KEY }}
        run: |
          # Create and unlock a temporary keychain
          security create-keychain -p "$CERT_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$CERT_PASSWORD" build.keychain

          # Decode the Base64 certificate
          echo "$CERTIFICATE" | base64 --decode > certificate.p12

          # Import the certificate into the keychain
          security import certificate.p12 -A -P "$CERT_PASSWORD" -k build.keychain

          # Explicitly trust the imported certificate
          CERT_HASH=$(security find-identity -v -p codesigning build.keychain | awk '/OnPage/ {print $2}')
          security set-key-partition-list -S apple-tool:,apple: -s -k "$CERT_PASSWORD" build.keychain

          # Verify identities for code signing
          security find-identity -v -p codesigning build.keychain

          # Run the build
          yarn run build:mac

      - name: Upload macOS ARM artifact
        uses: actions/upload-artifact@v3
        with:
          name: op-media-downloader-mac-arm
          path: dist/*.dmg

  release:
    needs:
      - build-windows
      - build-mac-intel
      - build-mac-arm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-windows
          path: release/windows

      - name: Download macOS Intel artifact
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-mac-intel
          path: release/mac-intel

      - name: Download macOS ARM artifact
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-mac-arm
          path: release/mac-arm

      - name: Upload assets to the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest release tag
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest release tag: $LATEST_RELEASE"

          if [ -z "$LATEST_RELEASE" ]; then
            echo "Error: No release found."
            exit 1
          fi

          # Debug: Validate the files exist
          ls -R release

          # Upload assets
          gh release upload "$LATEST_RELEASE" \
            release/windows/*.exe \
            release/mac-intel/*.dmg \
            release/mac-arm/*.dmg \
            --clobber
