name: Build and Release OP Media Downloader

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build for Windows
        run: yarn run build:win

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: op-media-downloader-windows
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Prepare signing certificate
        env:
          CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
          PRIVATE_KEY: ${{ secrets.MAC_PRIVATE_KEY }}
        run: |
          # Decode Base64-encoded certificate and private key
          echo "$CERTIFICATE" | base64 --decode > certificate.pem
          echo "$PRIVATE_KEY" | base64 --decode > private_key.pem

          # Combine certificate and private key into a PKCS12 file
          openssl pkcs12 -export \
            -inkey private_key.pem \
            -in certificate.pem \
            -out certificate.p12 \
            -password pass:""

      - name: Configure macOS keychain for signing
        run: |
          # Create a temporary keychain
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain

          # Import the certificate into the keychain
          security import certificate.p12 -k build.keychain -P "" -T /usr/bin/codesign

          # Allow codesign to access the key
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          # Verify the imported identities
          security find-identity -v -p codesigning build.keychain

      - name: Build and sign for macOS
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          yarn run build:mac

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: op-media-downloader-mac-${{ matrix.arch }}
          path: dist/*.dmg

  release:
    needs:
      - build-windows
      - build-mac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-windows
          path: release/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-mac-x64
          path: release/mac-x64

      - name: Download macOS ARM artifact
        uses: actions/download-artifact@v3
        with:
          name: op-media-downloader-mac-arm64
          path: release/mac-arm64

      - name: Upload assets to the latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest release tag
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest release tag: $LATEST_RELEASE"

          if [ -z "$LATEST_RELEASE" ]; then
            echo "Error: No release found."
            exit 1
          fi

          # Upload assets
          gh release upload "$LATEST_RELEASE" \
            release/windows/*.exe \
            release/mac-x64/*.dmg \
            release/mac-arm64/*.dmg \
            --clobber
